apiVersion: apps/v1
kind: Deployment
metadata:
  name: gyeongnam-nignx-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gyeongnam-nginx
  template:
    metadata:
      labels:
        app: gyeongnam-nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80